name:  KAmbieng

on:
#  schedule:
#    - cron: '0 0 */5 * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: 💩 Build 💩
        run: |
          bash data/00.sh

      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ github.token }}
          debug: true
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic update Rule Provider
